config/routes.rb
Rails.application.routes.draw do
  get 'showcase', to: 'showcase#index'
  get 'tools', to: 'tools#index'
  get 'kontakt', to: 'kontakt#index'
  get 'ueber_uns', to: 'ueber_uns#index'
  get 'startseite/index'



  root 'startseite#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kontakt_controller.rb
class KontaktController < ApplicationController
  def index
  end
end

app/controllers/showcase_controller.rb
class ShowcaseController < ApplicationController
  def index
  end
end

app/controllers/startseite_controller.rb
class StartseiteController < ApplicationController
  def index
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def index
  end
end

app/controllers/ueber_uns_controller.rb
class UeberUnsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kontakt_helper.rb
module KontaktHelper
end

app/helpers/showcase_helper.rb
module ShowcaseHelper
end

app/helpers/startseite_helper.rb
module StartseiteHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/helpers/ueber_uns_helper.rb
module UeberUnsHelper
end

app/views/kontakt/index.html.erb
<h1>Kontakt#index</h1>
<p>Find me in app/views/kontakt/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Web</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="<%= root_path %>">
        <%= image_tag("icon.svg", width: "30", height: "30", class: "d-inline-block align-top", alt: "") %>
        MySocials
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="<%= root_path %>">Startseite <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= ueber_uns_path %>">Über Uns</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= tools_path %>">Tools</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= showcase_path %>">Showcase</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= kontakt_path %>">Kontakt</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/showcase/index.html.erb
<h1>Showcase#index</h1>
<p>Find me in app/views/showcase/index.html.erb</p>

app/views/startseite/index.html.erb
<h1>Herzlich Willkommen</h1>

app/views/tools/index.html.erb
<h1>Tools#index</h1>
<p>Find me in app/views/tools/index.html.erb</p>

app/views/ueber_uns/index.html.erb
<h1>UeberUns#index</h1>
<p>Find me in app/views/ueber_uns/index.html.erb</p>